### ISSUE TITLE
Import file to configuration YAML

### ISSUE THREAD

**Issue by dannyjacobs** [HERA-Team/pyuvsim#26]
Extract the relevant simulation parameters from a data file to a YAML file suitable for input to the simulation.

**Comment by aelanman** [comment]
Currently available on the param_reader branch, there are two scripts relevant scripts.
- `uvfits_to_teleyaml.py` : Extracts antenna positions and telescope metadata from a uvfits file and writes out two configuration files. A .csv file contains antenna positions (in ENU/meters), beam ids, antenna names, and antenna numbers in a whitespace delimited (and justified) table. A yaml file contains telescope location, telescope name, number of antennas, and paths to beamfits files corresponding with different beam_ids.

-`uvfits_to_yaml.py` : Extracts time and frequency information from uvfits file and writes out a simulation yaml file.

**Note** That the user must still manually insert the correct teleyaml and antpos CSV  filenames, as well as source catalog and other keywords, into the simulation yaml file! 

I plan to put these functions in the simsetup.py module, instead of keeping them as scripts. They should be easier to find and callable by other functions for loopback tests and the like.

(I'm also open to suggestions for better names for these scripts and configuration files)
